PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX odfa: <http://purl.obolibrary.org/obo/OHD_0005009>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>

select ?iri where {
    ?iri oboInOwl:inSubset odfa:
}