## This query returns a count (i.e., number performed) for each type of procedure

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dental_procedure: <http://purl.obolibrary.org/obo/OHD_0000002>
PREFIX asserted_type:<http://purl.obolibrary.org/obo/OHD_0000092>

select ?restoration_procedure (count(distinct ?proci) as ?count) 
where 
{
  ## restoration procedure
  ## find each instance procedure and its asserted (i.e., direct) type
  ?proci rdf:type dental_procedure: .
  ?proci asserted_type: ?proct .
    
  ## assign label
  ?proct rdfs:label ?restoration_procedure .
  
}
group by ?restoration_procedure
order by desc(?count)
