#|
Created by: Bill Duncan
This file contains functions that are needed to generate OWL statements for dental findings in OHD.
Thus far findings are for:
- caries findings
- missing teeth findings
- unerupted teeth findings
|#

;;;; **** caries findings ****

(defun get-eaglesoft-caries-finding-iri (patient-id tooth-name instance-count)
  "Returns an iri for a 'caries finding' that is generated by the patient id, the name of the type of the tooth, and a count variable that differentiates multipe caries findings that are about the same tooth."
  (let ((uri nil))
    (setf uri 
	  (get-unique-individual-iri patient-id 
				     :salt *eaglesoft-salt*
				     :iri-base *eaglesoft-individual-teeth-iri-base*
				     :class-type !'caries finding'@ohd
				     :args `(,tooth-name ,instance-count "eaglesoft")))
    ;; return uri
    uri))

(defun get-eaglesoft-carious-lesion-iri (patient-id tooth-name instance-count)
  "Returns an iri for a carious lesion that is generated by the patient id, the name of the type of the tooth, and a count variable that differentiates multipe caries findings that are about the same tooth."
  (let ((uri nil))
    (setf uri 
	  (get-unique-individual-iri patient-id 
				     :salt *eaglesoft-salt*
				     :iri-base *eaglesoft-individual-teeth-iri-base*
				     :class-type !'carious lesion of tooth'@ohd
				     :args `(,tooth-name ,instance-count "eaglesoft")))
    ;; return uri
    uri))

;;;; **** missing teeth findings ****


;;;; **** unerupted teeth findings ****